[package]
name = "embroidery-fmt-jef"
version = "0.1.0"
authors = ["Opal Symes <code@opal.codes>"]
edition = "2018"

[dependencies]
byteorder = "1"
embroidery-lib = { path = "../../embroidery-lib" }

[dev-dependencies]
