[package]
name = "embroidery-fmt-svg"
version = "0.1.0"
authors = ["Opal Symes <code@opal.codes>"]
edition = "2018"

[dependencies]
embroidery-lib = { path = "../../embroidery-lib" }
svgtypes = "^0.1.1"
palette = "^0.4.1"
